services:
  - type: web
    name: inventory-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: MAIL_PROVIDER
        value: SENDGRID
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: DEMO_MODE
        value: "false"
      - key: OTP_MODE
        value: EMAIL
    autoDeploy: true
