// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo4W9V0h9WLfUK2tABzafZ1VizjdEBdCc',
    appId: '1:231449365632:web:1d017f3e43c3aa3ba85130',
    messagingSenderId: '231449365632',
    projectId: 'jms-spare-parts',
    authDomain: 'jms-spare-parts.firebaseapp.com',
    storageBucket: 'jms-spare-parts.firebasestorage.app',
    measurementId: 'G-DBV4YBCNHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo4W9V0h9WLfUK2tABzafZ1VizjdEBdCc',
    appId: '1:231449365632:android:7dbc4fc4b13b3530232a65',
    messagingSenderId: '231449365632',
    projectId: 'jms-spare-parts',
    storageBucket: 'jms-spare-parts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4W9V0h9WLfUK2tABzafZ1VizjdEBdCc',
    appId: '1:231449365632:ios:9975ba9c6837793aa85130',
    messagingSenderId: '231449365632',
    projectId: 'jms-spare-parts',
    storageBucket: 'jms-spare-parts.firebasestorage.app',
    iosBundleId: 'com.spareshub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo4W9V0h9WLfUK2tABzafZ1VizjdEBdCc',
    appId: '1:231449365632:web:ca269eaa09074d10a85130',
    messagingSenderId: '231449365632',
    projectId: 'jms-spare-parts',
    authDomain: 'jms-spare-parts.firebaseapp.com',
    storageBucket: 'jms-spare-parts.firebasestorage.app',
    measurementId: 'G-15SZYM8KSG',
  );
}
